:forae:
  - :fqdn: example.org
    :secure: false
    :test_on_init: false
    :cookies_auto_load: false
    :headless: true
    :app_root: /
    :driver: :firefox
    :platform_type: Test
    :log_to: log/test.log
    :log_level: :debug
    :dom_selectors:
    :cookies:
    # times in seconds; integers expected
    # These are the actual, configured wait values on the remote fora
    :waits:
      # delay between new topics
      :new_topic: 60
      :compose_topic: 10
      # delay between replies
      :new_reply: 15
      # delay between starting a reply and submitting the form
      :compose_reply: 5
    # how long to actually wait for the above (float allowed)
    :wait_multiplier: 1.5
    :dom_selectors:
      # TODO: special type; array of selectors when multiple click paths are required
      # CSS or XPath
      :topic_page:
        :type: :css
        :expression: 'CSS selector goes here'
        :returns: :one
      :topics_links:
        :type: :css
        :expression: 'CSS selector goes here'
        :returns: :many
      :my_topic:
        :type: :xpath
        :expression: 'XPath expression goes here'
        :returns: :one
      :my_replies:
        :type: :xpath
        :expression: 'XPath expression goes here'
        :returns: :many
      :replies_to_me:
        :type: :xpath
        :expression: 'xpath expression goes here'
        :returns: :many
      :locked_topic:
        :type: :xpath
        :expression: 'xpath expression goes here'
        :returns: :one
  - :fqdn: test.minichan.org
    :secure: false
    :test_on_init: false
    :app_root: /
    :driver: :firefox
    :platform_type: MiniBBS
    :log_level: :info
    :cookies:
      :SID: 's93vpuc3s7uqk8sj2phekfki31'
      :UID: '54c47463ba4da2.08700392'
      :password: 'Z4kAJyN4WZQ9VMZtfANuwBAMSrP0G9mN'
    # times in seconds; integers expected
    # These are the actual, configured wait values on the remote fora
    :waits:
      # delay between new topics
      :new_topic: 60
      :compose_topic: 10
      # delay between replies
      :new_reply: 15
      # delay between starting a reply and submitting the form
      :compose_reply: 5
    # how long to actually wait for the above (float allowed)
    :wait_multiplier: 1.5
    :dom_selectors:
      # TODO: special type; array of selectors when multiple click paths are required
      # CSS or XPath
      :topics_links:
        :type: :css
        :expression: '#body_wrapper .topic_headline a'
        :returns: :many
      :topic_page:
        :type: :css
        :expression: '#body_wrapper h3 span.reply_id'
        :returns: :one
      :locked_topic:
        :type: :xpath
        :expression: "//ul[@class='menu']/li[text()[contains(., 'Topic locked')]]"
        :returns: :one
      :my_topic:
        :type: :xpath
        :expression: "//h3[text()[contains(., '(you)')]]/following-sibling::div"
        :returns: :one
      :my_replies:
        :type: :xpath
        :expression: "//h3[text()[contains(., '(you)')]]/following-sibling::div[@class='body']"
        :returns: :many
      :replies_to_me:
        :type: :xpath
        :expression: "//span[@class='unimportant' and contains(text(),'(you)')][preceding::div[@class='body'][1]]"
        :returns: :many
  - :fqdn: minichan.org
    :secure: true
    :app_root: /
    :driver: :firefox
    :platform_type: MiniBBS
    :log_level: :info
    # These are the actual, configured wait values on the remote fora
    :waits:
      # delay between new topics
      :new_topic: 60
      :compose_topic: 10
      # delay between replies
      :new_reply: 15
      # delay between starting a reply and submitting the form
      :compose_reply: 5
    # how long to actually wait for the above (float allowed)
    :wait_multiplier: 4
    :dom_selectors:
      :topics_links: '#body_wrapper .topic_headline a'
      :my_topic: "//h3[text()[contains(., '(you)')]]/following-sibling::div"
      :my_replies: "//h3[text()[contains(., '(you)')]]/following-sibling::div"
      :replies_to_me: "//span[@class='unimportant' and contains(text(),'(you)')][preceding::div[@class='body'][1]]"
