test_uris:
  # URLs that respond to HTTP GET
  - '/stuff.php'
    platform: MiniBBS
    substring: 'Your personal settings'
  - '/member.php?action=register'
    platform: MyBB
    substring: 'Registration Agreement'

platforms:
  - MiniBBS:
    urls:
      root: '/'
  - MyBB:
    urls:
      root: '/'

