platforms:
  - :name: 'MiniBBS'
    :urls:
      :root: '/'
    :test:
      :uri: '/stuff.php'
      :substring: 'Your personal settings'
  - :name: 'MyBB'
    :urls:
      :root: '/'
    :test:
      :uri: '/member.php?action=register'
      :substring: 'Registration Agreement'
